services:
    pg:
        image: postgres:16
        restart: unless-stopped
        ports:
            - "7075:5432"
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=aslca
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - ntwrk

networks:
    ntwrk:
        driver: bridge

volumes:
    pg_data:
